/*
#aws_sns_platform _application
variable "application_name" {
  default     = "test_app"
  description = "The  application for sns"
}

/*variable "app_platform" {
  default     = "APNS"
  description = "The platform that the app is registered "
}
*
variable "platform_credential" {
  default     = "<APNS CERTIFICATE>"
  description = " The application platform credential"
}
*/
variable "name" {
  description = "The friendly name for the SNS topic. By default generated by Terraform."
}

variable "display_name" {
  description = "The display name for the SNS topic."
}

variable "protocol" {
  description = "mention the endpoint protocol such as http,email,sqs etc."
}

variable "endpoint" {
  description = "endpoint as per selected protocol."
}
